spring:
  datasource:
    url: jdbc:mysql://localhost:3306/second_project?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234
  jpa:
    show-sql: true