server:
  port: 19091

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/