services:
  mysql:
    image: mysql:8.0
    container_name: mysql-slack
    restart: always
    ports:
      - 3314:3306
    environment:
      MYSQL_ROOT_PASSWORD: sparta
      MYSQL_DATABASE: sparta_slack
      MYSQL_USER: slack_user
      MYSQL_PASSWORD: slack_password
    volumes:
      - mysql_data:/var/lib/mysql


volumes:
  mysql_data:
