EUREKA_NAME: localhost
EUREKA_HOST: eureka
EUREKA_PORT: 19090

SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3313
SPRING_DATASOURCE_USERNAME: root
SPRING_DATASOURCE_PASSWORD: root1234

REDIS_HOST: localhost
REDIS_PORT: 6379

SPRING_KAFKA_BOOTSTRAP_SERVERS: localhost:9092