EUREKA_NAME: localhost
EUREKA_HOST: eureka
EUREKA_PORT: 9090

SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/delivery-persons
SPRING_DATASOURCE_USERNAME: root
SPRING_DATASOURCE_PASSWORD: root1234

REDIS_HOST: localhost
REDIS_PORT: 6379

SPRING_KAFKA_BOOTSTRAP_SERVERS: localhost:9092

SECURITY_JWT_KEY: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"