services:
  mysql-user-db:
    image: mysql:8.0.34
    container_name: mysql-user
    ports:
      - "3315:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DATASOURCE_PASSWORD}
      MYSQL_DATABASE: user
    volumes:
      - mysql-data-user:/var/lib/mysql
    networks:
      - default
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data-user:

networks:
  default:
    driver: bridge